modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/MerchantPug/apugli/issues"

[[mods]]
modId="toomanyorigins"
version="${version}"
displayName="TooManyOrigins"
#updateJSONURL=""
displayURL="https://github.com/MerchantPug/toomanyorigins"
logoFile="pack.png"
authors="MerchantPug"
description="An addon to Origins loosely inspired by the original mod. "

[[dependencies.toomanyorigins]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="origins"
mandatory=true
versionRange="[1.20.1-1.10.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="apugli"
mandatory=true
versionRange="[2.9.0,)"
ordering="AFTER"
side="BOTH"