modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/MerchantPug/apugli/issues"

[[mods]]
modId="toomanyorigins"
version="${version}"
displayName="TooManyOrigins"
#updateJSONURL=""
displayURL="https://github.com/MerchantPug/toomanyorigins"
logoFile="pack.png"
authors="MerchantPug"
description="An addon to Origins in the spirit of the original mod."

[[dependencies.toomanyorigins]]
modId="forge"
mandatory=true
versionRange="[43.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="origins"
mandatory=true
versionRange="[1.19.2-1.7.1.0,)"
ordering="AFTER"
side="BOTH"